spring:
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        base-url: https://api.groq.com/openai
        options:
          model: llama-3.1-70b-versatile
  
management:
  endpoints:
    web:
      exposure:
        include: "*"